// generated by EnumJavaScriptSourceTool at 2022-03-15T20:21:13.47207

import SystemEnum from "../SystemEnum.js";
import SystemObject from "../SystemObject.js";

const TYPE_NAME = "font-style";

export default class FontStyle extends SystemEnum {
  
  static NORMAL = new FontStyle("NORMAL");
  static ITALIC = new FontStyle("ITALIC");
  static OBLIQUE = new FontStyle("OBLIQUE");
  
  static values() {
    return [
      FontStyle.NORMAL,
      FontStyle.ITALIC,
      FontStyle.OBLIQUE
    ];
  }
  
  static valueOf(name) {
    return SystemEnum.valueOf(name, "textStyle", FontStyle.values());
  }
  
  static fromJson(name) {
    return FontStyle.valueOf(name);
  }
  
  typeName() {
    return TYPE_NAME;
  }
}

SystemObject.register(TYPE_NAME, FontStyle.fromJson);
