// generated by EnumJavaScriptSourceTool at 2022-03-15T22:52:02.71579

import SystemEnum from "../SystemEnum.js";
import SystemObject from "../SystemObject.js";

const TYPE_NAME = "hyphens";

export default class Hyphens extends SystemEnum {
  
  static NONE = new Hyphens("NONE");
  static MANUAL = new Hyphens("MANUAL");
  static AUTO = new Hyphens("AUTO");
  
  static values() {
    return [
      Hyphens.NONE,
      Hyphens.MANUAL,
      Hyphens.AUTO
    ];
  }
  
  static valueOf(name) {
    return SystemEnum.valueOf(name, "textStyle", Hyphens.values());
  }
  
  static fromJson(name) {
    return Hyphens.valueOf(name);
  }
  
  typeName() {
    return TYPE_NAME;
  }
}

SystemObject.register(TYPE_NAME, Hyphens.fromJson);
