import BorderCollapse from "./BorderCollapse.js";
import BorderStyle from "./BorderStyle.js";
import Direction from "./Direction.js"
import FontKerning from "./FontKerning.js";
import FontStretch from "./FontStretch.js";
import FontStyle from "./FontStyle.js";
import FontVariant from "./FontVariant.js";
import HangingPunctuation from "./HangingPunctuation.js";
import Hyphens from "./Hyphens.js";
import ListStylePosition from "./ListStylePosition.js";
import ListStyleType from "./ListStyleType.js";
import OutlineStyle from "./OutlineStyle.js";
import Overflow from "./Overflow.js";
import TextAlign from "./TextAlign.js";
import TextDecorationLine from "./TextDecorationLine.js";
import TextDecorationStyle from "./TextDecorationStyle.js";
import TextJustify from "./TextJustify.js";
import TextTransform from "./TextTransform.js";
import TextWrapping from "./TextWrapping.js";
import TextStyle from "./TextStyle.js";
import TextWhitespace from "./TextWhitespace.js";
import VerticalAlign from "./VerticalAlign.js";
import Visibility from "./Visibility.js";
import WritingMode from "./WritingMode.js";
import WordWrap from "./WordWrap.js";
import WordBreak from "./WordBreak.js";

// generated by TextStylePropertyNameToEnumValuesFunctionJavaScriptSourceTool at 2021-03-28T15:04:22.250177
export default function stylePropertyNameToEnum(property) {
    let values;

    switch(property) {
        case TextStyle.BORDER_BOTTOM_STYLE:
            values = BorderStyle.values();
            break;
        case TextStyle.BORDER_COLLAPSE:
            values = BorderCollapse.values();
            break;
        case TextStyle.BORDER_LEFT_STYLE:
            values = BorderStyle.values();
            break;
        case TextStyle.BORDER_RIGHT_STYLE:
            values = BorderStyle.values();
            break;
        case TextStyle.BORDER_TOP_STYLE:
            values = BorderStyle.values();
            break;
        case TextStyle.DIRECTION:
            values = Direction.values();
            break;
        case TextStyle.FONT_KERNING:
            values = FontKerning.values();
            break;
        case TextStyle.FONT_STRETCH:
            values = FontStretch.values();
            break;
        case TextStyle.FONT_STYLE:
            values = FontStyle.values();
            break;
        case TextStyle.FONT_VARIANT:
            values = FontVariant.values();
            break;
        case TextStyle.HANGING_PUNCTUATION:
            values = HangingPunctuation.values();
            break;
        case TextStyle.HYPHENS:
            values = Hyphens.values();
            break;
        case TextStyle.LIST_STYLE_POSITION:
            values = ListStylePosition.values();
            break;
        case TextStyle.LIST_STYLE_TYPE:
            values = ListStyleType.values();
            break;
        case TextStyle.OUTLINE_STYLE:
            values = OutlineStyle.values();
            break;
        case TextStyle.OVERFLOW_X:
            values = Overflow.values();
            break;
        case TextStyle.OVERFLOW_Y:
            values = Overflow.values();
            break;
        case TextStyle.TEXT_ALIGN:
            values = TextAlign.values();
            break;
        case TextStyle.TEXT_DECORATION_LINE:
            values = TextDecorationLine.values();
            break;
        case TextStyle.TEXT_DECORATION_STYLE:
            values = TextDecorationStyle.values();
            break;
        case TextStyle.TEXT_JUSTIFY:
            values = TextJustify.values();
            break;
        case TextStyle.TEXT_TRANSFORM:
            values = TextTransform.values();
            break;
        case TextStyle.TEXT_WRAPPING:
            values = TextWrapping.values();
            break;
        case TextStyle.VERTICAL_ALIGN:
            values = VerticalAlign.values();
            break;
        case TextStyle.VISIBILITY:
            values = Visibility.values();
            break;
        case TextStyle.WHITE_SPACE:
            values = TextWhitespace.values();
            break;
        case TextStyle.WORD_BREAK:
            values = WordBreak.values();
            break;
        case TextStyle.WORD_WRAP:
            values = WordWrap.values();
            break;
        case TextStyle.WRITING_MODE:
            values = WritingMode.values();
            break;
        default:
            throw new Error("Invalid style property \" + property + \"");
    }
    return values;
}
