// generated by EnumJavaScriptSourceTool at 2022-10-10T19:15:23.224798

import SystemEnum from "../SystemEnum.js";
import SystemObject from "../SystemObject.js";

const TYPE_NAME = "spreadsheet-error-kind";

export default class SpreadsheetErrorKind extends SystemEnum {
  
  static NULL = new SpreadsheetErrorKind("NULL");
  static DIV0 = new SpreadsheetErrorKind("DIV0");
  static VALUE = new SpreadsheetErrorKind("VALUE");
  static REF = new SpreadsheetErrorKind("REF");
  static NAME = new SpreadsheetErrorKind("NAME");
  static NAME_STRING = new SpreadsheetErrorKind("NAME_STRING");
  static NUM = new SpreadsheetErrorKind("NUM");
  static NA = new SpreadsheetErrorKind("NA");
  static ERROR = new SpreadsheetErrorKind("ERROR");
  static SPILL = new SpreadsheetErrorKind("SPILL");
  static CALC = new SpreadsheetErrorKind("CALC");
  
  static values() {
    return [
      SpreadsheetErrorKind.NULL,
      SpreadsheetErrorKind.DIV0,
      SpreadsheetErrorKind.VALUE,
      SpreadsheetErrorKind.REF,
      SpreadsheetErrorKind.NAME,
      SpreadsheetErrorKind.NAME_STRING,
      SpreadsheetErrorKind.NUM,
      SpreadsheetErrorKind.NA,
      SpreadsheetErrorKind.ERROR,
      SpreadsheetErrorKind.SPILL,
      SpreadsheetErrorKind.CALC
    ];
  }
  
  static valueOf(name) {
    return SystemEnum.valueOf(name, "SpreadsheetErrorKind", SpreadsheetErrorKind.values());
  }
  
  static fromJson(name) {
    return SpreadsheetErrorKind.valueOf(name);
  }
  
  typeName() {
    return TYPE_NAME;
  }
}

SystemObject.register(TYPE_NAME, SpreadsheetErrorKind.fromJson);
