// generated by EnumJavaScriptSourceTool at 2022-03-15T22:52:02.56619

import SystemEnum from "../../../SystemEnum.js";
import SystemObject from "../../../SystemObject.js";

const TYPE_NAME = "spreadsheet-viewport-selection-navigation";

export default class SpreadsheetViewportSelectionNavigation extends SystemEnum {
  
  static LEFT_COLUMN = new SpreadsheetViewportSelectionNavigation("LEFT_COLUMN");
  static UP_ROW = new SpreadsheetViewportSelectionNavigation("UP_ROW");
  static RIGHT_COLUMN = new SpreadsheetViewportSelectionNavigation("RIGHT_COLUMN");
  static DOWN_ROW = new SpreadsheetViewportSelectionNavigation("DOWN_ROW");
  static EXTEND_LEFT_COLUMN = new SpreadsheetViewportSelectionNavigation("EXTEND_LEFT_COLUMN");
  static EXTEND_UP_ROW = new SpreadsheetViewportSelectionNavigation("EXTEND_UP_ROW");
  static EXTEND_RIGHT_COLUMN = new SpreadsheetViewportSelectionNavigation("EXTEND_RIGHT_COLUMN");
  static EXTEND_DOWN_ROW = new SpreadsheetViewportSelectionNavigation("EXTEND_DOWN_ROW");
  
  static values() {
    return [
      SpreadsheetViewportSelectionNavigation.LEFT_COLUMN,
      SpreadsheetViewportSelectionNavigation.UP_ROW,
      SpreadsheetViewportSelectionNavigation.RIGHT_COLUMN,
      SpreadsheetViewportSelectionNavigation.DOWN_ROW,
      SpreadsheetViewportSelectionNavigation.EXTEND_LEFT_COLUMN,
      SpreadsheetViewportSelectionNavigation.EXTEND_UP_ROW,
      SpreadsheetViewportSelectionNavigation.EXTEND_RIGHT_COLUMN,
      SpreadsheetViewportSelectionNavigation.EXTEND_DOWN_ROW
    ];
  }
  
  static valueOf(name) {
    return SystemEnum.valueOf(name, "navigation", SpreadsheetViewportSelectionNavigation.values());
  }
  
  static fromJson(name) {
    return SpreadsheetViewportSelectionNavigation.valueOf(name);
  }
  
  static from(text) {
    return SystemObject.from(text, "navigation", SpreadsheetViewportSelectionNavigation.value());
  }
  
  typeName() {
    return TYPE_NAME;
  }

  toQueryString() {
    return this.name()
        .toLowerCase()
        .replace("_", "-" )
        .replace("-column", " column")
        .replace("-row", " row");
  }
}

SystemObject.register(TYPE_NAME, SpreadsheetViewportSelectionNavigation.fromJson);
