// generated by EnumJavaScriptSourceTool at 2022-03-15T22:52:02.56619

import SystemEnum from "../../../SystemEnum.js";
import SystemObject from "../../../SystemObject.js";

const TYPE_NAME = "spreadsheet-viewport-navigation";

export default class SpreadsheetViewportNavigation extends SystemEnum {
  
  static LEFT_COLUMN = new SpreadsheetViewportNavigation("LEFT_COLUMN");
  static UP_ROW = new SpreadsheetViewportNavigation("UP_ROW");
  static RIGHT_COLUMN = new SpreadsheetViewportNavigation("RIGHT_COLUMN");
  static DOWN_ROW = new SpreadsheetViewportNavigation("DOWN_ROW");
  static EXTEND_LEFT_COLUMN = new SpreadsheetViewportNavigation("EXTEND_LEFT_COLUMN");
  static EXTEND_UP_ROW = new SpreadsheetViewportNavigation("EXTEND_UP_ROW");
  static EXTEND_RIGHT_COLUMN = new SpreadsheetViewportNavigation("EXTEND_RIGHT_COLUMN");
  static EXTEND_DOWN_ROW = new SpreadsheetViewportNavigation("EXTEND_DOWN_ROW");
  
  static values() {
    return [
      SpreadsheetViewportNavigation.LEFT_COLUMN,
      SpreadsheetViewportNavigation.UP_ROW,
      SpreadsheetViewportNavigation.RIGHT_COLUMN,
      SpreadsheetViewportNavigation.DOWN_ROW,
      SpreadsheetViewportNavigation.EXTEND_LEFT_COLUMN,
      SpreadsheetViewportNavigation.EXTEND_UP_ROW,
      SpreadsheetViewportNavigation.EXTEND_RIGHT_COLUMN,
      SpreadsheetViewportNavigation.EXTEND_DOWN_ROW
    ];
  }
  
  static valueOf(name) {
    return SystemEnum.valueOf(name, "navigation", SpreadsheetViewportNavigation.values());
  }
  
  static fromJson(name) {
    return SpreadsheetViewportNavigation.valueOf(name);
  }
  
  static from(text) {
    return SystemObject.from(text, "navigation", SpreadsheetViewportNavigation.value());
  }
  
  typeName() {
    return TYPE_NAME;
  }

  toQueryString() {
    return this.name()
        .toLowerCase()
        .replace("_", "-" )
        .replace("-column", " column")
        .replace("-row", " row");
  }
}

SystemObject.register(TYPE_NAME, SpreadsheetViewportNavigation.fromJson);
