// generated by EnumJavaScriptSourceTool at 2022-03-15T21:21:34.559642

import SystemEnum from "../../SystemEnum.js";
import SystemObject from "../../SystemObject.js";

const TYPE_NAME = "spreadsheet-reference-kind";

export default class SpreadsheetReferenceKind extends SystemEnum {
  
  static ABSOLUTE = new SpreadsheetReferenceKind("ABSOLUTE");
  static RELATIVE = new SpreadsheetReferenceKind("RELATIVE");
  
  static values() {
    return [
      SpreadsheetReferenceKind.ABSOLUTE,
      SpreadsheetReferenceKind.RELATIVE
    ];
  }
  
  static valueOf(name) {
    return SystemEnum.valueOf(name, "SpreadsheetReferenceKind", SpreadsheetReferenceKind.values());
  }
  
  static fromJson(name) {
    return SpreadsheetReferenceKind.valueOf(name);
  }
  
  prefix() {
    return SpreadsheetReferenceKind.ABSOLUTE === this ?
      "$" :
      "" ;
  }
  
  typeName() {
    return TYPE_NAME;
  }
}

SystemObject.register(TYPE_NAME, SpreadsheetReferenceKind.fromJson);
