// generated by EnumJavaScriptSourceTool at 2021-04-03T13:17:12.30458

import SystemEnum from "../SystemEnum.js";
import SystemObject from "../SystemObject.js";

const TYPE_NAME = "expression-number-kind";

export default class ExpressionNumberKind extends SystemEnum {
  
  static BIG_DECIMAL = new ExpressionNumberKind("BIG_DECIMAL");
  static DOUBLE = new ExpressionNumberKind("DOUBLE");
  
  static values() {
    return [
      ExpressionNumberKind.BIG_DECIMAL,
      ExpressionNumberKind.DOUBLE
    ];
  }
  
  static valueOf(name) {
    return SystemEnum.valueOf(name, ExpressionNumberKind.values());
  }
  
  static fromJson(name) {
    return ExpressionNumberKind.valueOf(name);
  }
  
  typeName() {
    return TYPE_NAME;
  }
}

SystemObject.register(TYPE_NAME, ExpressionNumberKind.fromJson);
